version: '3'
services:
  llm_ui:
    build: .
    network_mode: host
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=localhost
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
