version: '3'
services:
  db:
      image: postgres:latest
      environment:
        - POSTGRES_USER=ollama_tutorial
        - POSTGRES_PASSWORD=ollama_tutorial
        - POSTGRES_DB=ollama_tutorial
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"

